# from datetime import datetime

# current_dateTime = datetime.now()

# print(current_dateTime)
# print(current_dateTime.year)  # 2022

# print(current_dateTime.month)  # 9

# print(current_dateTime.day)  # 20
# patience is a virtue

# import xlwt
# from datetime import date, timedelta

# book = xlwt.Workbook(encoding="utf-8")
# sheet1 = book.add_sheet("Sheet 1")

# start_date = date(2024, 3, 10)
# end_date = date(2025, 1, 1)  # perhaps date.now()

# delta = end_date - start_date  # returns timedelta
# row = 0
# column = 0
# for i in range(delta.days + 1):
#     day = start_date + timedelta(days=i)
#     sheet1.write(row, column, day.strftime("%m/%d"))
#     row += 1
#     if row > 6:
#         column +=1
#         row = 0

# book.save("trial.xls")

from datetime import date, timedelta

start_date = date(2024, 3, 10)
end_date = date(2025, 1, 1)
delta = end_date - start_date
rslt = {}
for i in range(delta.days + 1):
    day = start_date + timedelta(days=i)
    c_year = day.year
    c_month = day.month
    c_day = day.day
    if c_year not in rslt:
        rslt[c_year] = {}
    if c_month not in rslt[c_year]:
        rslt[c_year][c_month] = {}
    rslt[c_year][c_month][c_day] = 'low_push'
print(rslt)
high_push = 6
low_push = 2
{
    2024: {
        3: {
            10: high_push,
            11: high_push,
            12: high_push,
            13: high_push,
            14: high_push,
            15: high_push,
            16: high_push,
            17: low_push,
            18: low_push,
            19: low_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: high_push,
            26: high_push,
            27: high_push,
            28: high_push,
            29: high_push,
            30: low_push,
            31: low_push,
        },
        4: {
            1: high_push,
            2: low_push,
            3: high_push,
            4: low_push,
            5: low_push,
            6: low_push,
            7: low_push,
            8: low_push,
            9: high_push,
            10: low_push,
            11: low_push,
            12: low_push,
            13: low_push,
            14: low_push,
            15: low_push,
            16: low_push,
            17: low_push,
            18: low_push,
            19: low_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: high_push,
            24: high_push,
            25: high_push,
            26: high_push,
            27: low_push,
            28: low_push,
            29: high_push,
            30: low_push,
        },
        5: {
            1: high_push,
            2: low_push,
            3: low_push,
            4: low_push,
            5: low_push,
            6: low_push,
            7: high_push,
            8: high_push,
            9: high_push,
            10: high_push,
            11: low_push,
            12: low_push,
            13: low_push,
            14: low_push,
            15: low_push,
            16: low_push,
            17: low_push,
            18: low_push,
            19: low_push,
            20: high_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: low_push,
            27: high_push,
            28: low_push,
            29: low_push,
            30: low_push,
            31: low_push,
        },
        6: {
            1: low_push,
            2: low_push,
            3: high_push,
            4: high_push,
            5: high_push,
            6: high_push,
            7: high_push,
            8: low_push,
            9: low_push,
            10: high_push,
            11: low_push,
            12: low_push,
            13: low_push,
            14: low_push,
            15: low_push,
            16: low_push,
            17: high_push,
            18: low_push,
            19: low_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: low_push,
            27: low_push,
            28: low_push,
            29: low_push,
            30: low_push,
        },
        7: {
            1: high_push,
            2: low_push,
            3: low_push,
            4: low_push,
            5: high_push,
            6: low_push,
            7: low_push,
            8: high_push,
            9: high_push,
            10: high_push,
            11: high_push,
            12: high_push,
            13: low_push,
            14: low_push,
            15: high_push,
            16: low_push,
            17: low_push,
            18: low_push,
            19: high_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: low_push,
            27: low_push,
            28: low_push,
            29: high_push,
            30: high_push,
            31: high_push,
        },
        8: {
            1: high_push,
            2: high_push,
            3: low_push,
            4: low_push,
            5: high_push,
            6: low_push,
            7: high_push,
            8: low_push,
            9: high_push,
            10: low_push,
            11: low_push,
            12: high_push,
            13: low_push,
            14: high_push,
            15: low_push,
            16: high_push,
            17: low_push,
            18: low_push,
            19: low_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: high_push,
            27: high_push,
            28: high_push,
            29: high_push,
            30: high_push,
            31: low_push,
        },
        9: {
            1: low_push,
            2: low_push,
            3: high_push,
            4: low_push,
            5: low_push,
            6: low_push,
            7: low_push,
            8: low_push,
            9: low_push,
            10: low_push,
            11: high_push,
            12: low_push,
            13: low_push,
            14: low_push,
            15: low_push,
            16: low_push,
            17: low_push,
            18: low_push,
            19: high_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: high_push,
            24: high_push,
            25: high_push,
            26: high_push,
            27: high_push,
            28: low_push,
            29: low_push,
            30: low_push,
        },
        10: {
            1: low_push,
            2: low_push,
            3: low_push,
            4: low_push,
            5: low_push,
            6: low_push,
            7: high_push,
            8: high_push,
            9: high_push,
            10: high_push,
            11: high_push,
            12: low_push,
            13: low_push,
            14: high_push,
            15: low_push,
            16: low_push,
            17: low_push,
            18: high_push,
            19: low_push,
            20: low_push,
            21: high_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: high_push,
            26: low_push,
            27: low_push,
            28: low_push,
            29: low_push,
            30: low_push,
            31: low_push,
        },
        11: {
            1: low_push,
            2: low_push,
            3: low_push,
            4: high_push,
            5: high_push,
            6: high_push,
            7: high_push,
            8: high_push,
            9: low_push,
            10: low_push,
            11: high_push,
            12: low_push,
            13: high_push,
            14: low_push,
            15: high_push,
            16: low_push,
            17: low_push,
            18: high_push,
            19: low_push,
            20: high_push,
            21: low_push,
            22: high_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: low_push,
            27: low_push,
            28: low_push,
            29: low_push,
            30: low_push,
        },
        12: {
            1: low_push,
            2: low_push,
            3: low_push,
            4: low_push,
            5: low_push,
            6: low_push,
            7: low_push,
            8: low_push,
            9: low_push,
            10: low_push,
            11: low_push,
            12: low_push,
            13: low_push,
            14: low_push,
            15: low_push,
            16: low_push,
            17: low_push,
            18: low_push,
            19: low_push,
            20: low_push,
            21: low_push,
            22: low_push,
            23: low_push,
            24: low_push,
            25: low_push,
            26: low_push,
            27: low_push,
            28: low_push,
            29: low_push,
            30: low_push,
            31: low_push,
        },
    },
    2025: {1: {1: low_push}},
}
